{"name": "Безуспешный логин пользователя с неуказанным паролем.", "status": "passed", "description": "Попытка логина с неверными данными.", "start": 1711211947721, "stop": 1711211948056, "uuid": "87275af1-3324-41ba-b7f4-5606d6ced2c1", "historyId": "9b42beda61d82a576b8557a5aa4292fc", "testCaseId": "9b42beda61d82a576b8557a5aa4292fc", "fullName": "tests.test_user_login.TestLogin#test_unsuccessful_login_with_wrong_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "bna-A520M-DS3H"}, {"name": "thread", "value": "373412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}