{"name": "Безуспешный логин пользователя с неуказанным паролем.", "status": "passed", "description": "Попытка логина с неверными данными.", "start": 1711208311432, "stop": 1711208311738, "uuid": "4cd1e8bd-8574-4cd7-b18e-eeb24bd701e9", "historyId": "9b42beda61d82a576b8557a5aa4292fc", "testCaseId": "9b42beda61d82a576b8557a5aa4292fc", "fullName": "tests.test_user_login.TestLogin#test_unsuccessful_login_with_wrong_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "bna-A520M-DS3H"}, {"name": "thread", "value": "371293-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}